Update Dockerfile

diff --git a/SyncTube/Dockerfile b/SyncTube/Dockerfile
--- a/SyncTube/Dockerfile
+++ b/SyncTube/Dockerfile
@@ -4,10 +4,14 @@ WORKDIR /app
 
 COPY . .
 
+RUN pwd
+RUN ls -la
+RUN test -f pom.xml && echo "pom.xml found" || echo "pom.xml NOT found"
+
 RUN apt-get update && apt-get install -y maven
 
-RUN mvn clean package -DskipTests
+RUN mvn -f pom.xml clean package -DskipTests
 
 EXPOSE 8089
 
-ENTRYPOINT ["java","-jar","target/SyncTube-0.0.1-SNAPSHOT.jar"]
+CMD ["java","-jar","target/SyncTube-0.0.1-SNAPSHOT.jar"]
